recorder:
  recorder-dir: E:\\live stream  # 录播姬工作目录
  process-dir: E:\\live stream\proceed  # 输出位置
  delete-after-upload: true  # 是否在上传完成后删除

server:
  port: 8866 # 运行端口
  webhooks:  # webhook, 在上传完成后触发

account:
  username: your account # 账号
  password: your password # 密码
