recorder:
  recorder-dir:  # 录播姬工作目录
  process-dir:  # 输出位置
  delete-after-upload:  # 是否在上传完成后删除
  is-docker:  # 是否使用docker
  workers:  # 处理视频线程数

server:
  port: # 运行端口
  webhooks: # webhook, 在上传完成后触发
