rooms:
  - id: 21797866  # 需要上传的直播间 ID，长号短号均可
    tags: 3号直播,test # 上传所需的tag，英文逗号分割
    title: ${title} ${time} # 视频标题，可以使用模版
    description:  # 视频描述
      test application
    conditions:  # 额外的tag条件，注意判断逻辑为&
    - item: name # 字段，例如title
      regexp: 3 # 匹配的正则
      tags: 3a # 该条件下额外的tag
      process: true # 当匹配到对应条件时是否处理，默认为true
